name: Continuous Code Formatting

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Format code
        uses: actionsx/prettier@v3
        with:
          # 核心改动：去掉前面的空格或特殊格式，确保它是一段纯文本
          args: --write **/*.{html,css,js,json,py}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
